[project]
name = "sen5x"
version = "0.2.0"
description = "Simple bindings for the SEN5x C library"
readme = "README.md"
authors = [{ name = "Marcin Cieślak", email = "marcin.k.cieslak@gmail.com" }]
requires-python = ">=3.11, <3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.10.0,<0.12"]
build-backend = "uv_build"
